version: "3.1"

services:
  db:
    image: postgres:12.0
    container_name: boilerplate_postgres
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: boilerplate_dev
      POSGRES_PASSWORD: boilerplate_dev
    ports:
      - "5432:5432"
